# Generated by Django 4.0.6 on 2022-11-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsi', '0002_auto_20210517_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp153', max_length=70),
        ),
    ]
